fullname: Andrey Marakulin
favicon: /assets/images/favicon.svg
logo: /assets/images/photo.png

show_info: true
age: 23 y.o.
location: Sirius, Russia
language: Russian, English

show_contacts: true
mailto: mailto:annndruha.github@gmail.com
cv_pdf_link: https://raw.githubusercontent.com/Annndruha/annndruha.github.io/main/pdf/cv_pdf.pdf

remote_theme: annndruha/minimal-resume
plugins:
- jekyll-remote-theme
